name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      backend_version: ${{ steps.setver.outputs.backend }}
      frontend_version: ${{ steps.setver.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker versions
        id: setver
        run: |
          dockerhub_user="alioth360"

          # Get latest tags from Docker Hub
          get_next_version() {
            local repo=$1
            latest=$(curl -s https://hub.docker.com/v2/repositories/$repo/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+$' | sort -V | tail -n1)
            if [ -z "$latest" ]; then
              echo "1.0"
            else
              major=$(echo "$latest" | cut -d. -f1)
              minor=$(echo "$latest" | cut -d. -f2)
              echo "$major.$((minor + 1))"
            fi
          }

          backend_version=$(get_next_version "$dockerhub_user/node-backend")
          frontend_version=$(get_next_version "$dockerhub_user/nginx-frontend")

          echo "backend=$backend_version" >> $GITHUB_OUTPUT
          echo "frontend=$frontend_version" >> $GITHUB_OUTPUT

  build-backend:
    needs: set-version
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'backend') || contains(github.event.head_commit.message, 'Backend') }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t alioth360/node-backend:${{ needs.set-version.outputs.backend_version }} ./backend
          docker push alioth360/node-backend:${{ needs.set-version.outputs.backend_version }}

  build-frontend:
    needs: set-version
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'frontend') || contains(github.event.head_commit.message, 'Frontend') }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t alioth360/nginx-frontend:${{ needs.set-version.outputs.frontend_version }} ./frontend
          docker push alioth360/nginx-frontend:${{ needs.set-version.outputs.frontend_version }}
