name: Auto Build & Push with Versioning

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - main

env:
  DOCKERHUB_USERNAME: alioth360

jobs:
  backend:
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.modified), 'backend/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Get latest backend tag and increment
      id: get_version
      run: |
        latest=$(curl -s https://hub.docker.com/v2/repositories/${{ env.DOCKERHUB_USERNAME }}/node-backend/tags | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+$' | sort -V | tail -1)
        echo "Latest tag: $latest"
        version=$(awk -F. '{printf "%d.%d", $1, $2 + 1}' <<< "$latest")
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Build Backend Docker Image
      run: docker build -t $DOCKERHUB_USERNAME/node-backend:$VERSION ./backend

    - name: Push Backend Image
      run: docker push $DOCKERHUB_USERNAME/node-backend:$VERSION

  frontend:
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.modified), 'frontend/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Get latest frontend tag and increment
      id: get_version
      run: |
        latest=$(curl -s https://hub.docker.com/v2/repositories/${{ env.DOCKERHUB_USERNAME }}/nginx-frontend/tags | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+$' | sort -V | tail -1)
        echo "Latest tag: $latest"
        version=$(awk -F. '{printf "%d.%d", $1, $2 + 1}' <<< "$latest")
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Build Frontend Docker Image
      run: docker build -t $DOCKERHUB_USERNAME/nginx-frontend:$VERSION ./frontend

    - name: Push Frontend Image
      run: docker push $DOCKERHUB_USERNAME/nginx-frontend:$VERSION
